# Configures JSON-LD conversion from IuMetadata::Mods/Marc attributes
#
---
"@context":
  id: "@id"
  dc: http://purl.org/dc/elements/1.1/
  dcterms: http://purl.org/dc/terms/
  iiif: http://iiif.io/api/presentation/2#
  loc: http://id.loc.gov/vocabulary/identifiers/
  mods: http://www.loc.gov/mods/rdf/v1#
  pulterms: http://library.princeton.edu/terms/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  skos: http://www.w3.org/2004/02/skos/core#
  title:
    "@id": dcterms:title
  identifier:
    "@id": ebucore:identifier
  unit_of_origin:
    "@id": bf:heldBy
  digitized_by_entity:
    "@id": ebucore:hasCreator
  digitized_by_staff:
    "@id": ebucore:hasMetadataAttributor
  extraction_workstation:
    "@id": skos:note
  #Playback Calibration:
  #  "@id": skos:note
 digitization_comments:
    "@id": ebucore:comments
  original_identifier:
    "@id": ebucore:hasSource
  original_format:
    "@id": dc:format
  recording_standard:
    "@id": ebucore:hasStandard
  Tape Stock Brand:
    "@id": ebucore:medium
  image_format:
    "@id": ebucore:aspectRatio
  definition:
    "@id": ebucore:hasVideoFormat
  Original Media Damage:
    "@id": skos:historyNote
  Original Media Preservation Problem:
    "@id": skos:scopeNote
  QC Status:
    "@id": skos:changeNote
  Manual QC Check:
    "@id": skos:changeNote
  Encoder Manufacturer:
    "@id": premis:hasHardwareOtherInformation
  Encoder Model:
    "@id": premis:hasHardwareOtherInformation
  Encoder Serial Number:
    "@id": premis:hasHardwareOtherInformation
  AD Manufacturer:
    "@id": premis:hasHardwareName
  AD Model:
    "@id": premis:hasHardwareName
  AD Serial Number:
    "@id": premis:hasHardwareName
  Speed Used:
    "@id": ebucore:playbackSpeed
  TBC Manufacturer:
    "@id": premis:hasHardwareName
  TBC Model:
    "@id": premis:hasHardwareName
  TBC Serial Number:
    "@id": premis:hasHardwareName
  Tape Thickness:
    "@id": dcterms:description
  Total Parts:
    "@id": ebucore:partTotalNumber
  date_generated:
    "@id": ebucore:dateCreated
  file_format:
    "@id": premis:hasFormatName
  file_format_long_name:
    "@id": ebucore:hasFileFormat
  codec_type:
    "@id": ebucore:hasMedium
  codec_name:
    "@id": ebucore:hasCode
  codec_long_name:
    "@id": ebucore:codecName
  duration:
    "@id": ebucore:duration
  bit_rate:
    "@id": ebucore:bitRate
  file_name:
    "@id": ebucore:filename
  file_size:
    "@id": ebucore:fileSize
  identifier:
    "@id": ebucore:identifier
  unit_of_origin:
    "@id": ebucore:comments
  Unit of Origin Statement:
    "@id": ebucore:comments
  Alternative Unit of Origin Statement:
    "@id": ebucore:comments
  Part:
    "@id": ebucore:partNumber
  sample_rate:
    "@id": ebucore:sampleRate
  Video Width:
    "@id": ebucore:width
  Video Height:
    "@id": ebucore:height
  MD5 Checksum:
    "@id": nfo:hashValue
  

