development:
  host: http://localhost
  port: 3001
  store: SDA
  cache: SDADisk
  api_prefix:
  store_path: stores
  store_files_path: files
  cache_path: caches
  cache_files_path: files
test:
  host: http://localhost
  port: 3001
  store: SDA
  cache: SDADisk
  api_prefix:
  store_path: stores
  store_files_path: files
  cache_path: caches
  cache_files_path: files
production:
  host: localhost
  port: 3001
  store: SDA
  cache: SDADisk
