development:
  host: http://helium.dlib.indiana.edu
  port: 8200
  store: SDA
  cache: SDADisk
test:
  host: http://helium.dlib.indiana.edu
  port: 8200
  store: SDA
  cache: SDADisk
production:
  host: localhost
  port: 3001
  store: SDA
  cache: SDADisk
