development:
  host: http://localhost
  port: 3001
  store: SDA
  cache: SDADisk
test:
  host: http://localhost
  port: 3001
  store: SDA
  cache: SDADisk
production:
  host: localhost
  port: 3001
  store: SDA
  cache: SDADisk
